# name of your github action
name: build
# this will help you specify where to run 
on:
  push:
    branches:
    # this will run on the electron branch
      - electron
      
build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: feature/github-actions        
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: see directory
      run: ls      
